export const ACHIEVEMENTS = [
  { key: "account_created", category: "onboarding", tier: "bronze", points: 10, sortOrder: 10, icon: "spark" },
  { key: "first_match", category: "onboarding", tier: "bronze", points: 20, sortOrder: 20, icon: "paddle" },
  { key: "first_win", category: "performance", tier: "bronze", points: 30, sortOrder: 30, icon: "trophy" },
  { key: "first_singles", category: "activity", tier: "bronze", points: 25, sortOrder: 32, icon: "paddle" },
  { key: "singles_10", category: "activity", tier: "silver", points: 70, sortOrder: 33, icon: "paddle" },
  { key: "first_doubles", category: "activity", tier: "bronze", points: 25, sortOrder: 34, icon: "steps" },
  { key: "doubles_10", category: "activity", tier: "silver", points: 70, sortOrder: 34, icon: "steps" },
  { key: "matches_3", category: "activity", tier: "bronze", points: 25, sortOrder: 35, icon: "steps" },
  { key: "matches_5", category: "activity", tier: "bronze", points: 35, sortOrder: 37, icon: "steps" },
  { key: "matches_10", category: "activity", tier: "silver", points: 50, sortOrder: 40, icon: "steps" },
  { key: "matches_25", category: "activity", tier: "gold", points: 100, sortOrder: 50, icon: "crown" },
  { key: "matches_50", category: "activity", tier: "gold", points: 150, sortOrder: 55, icon: "crown" },
  { key: "matches_100", category: "activity", tier: "platinum", points: 260, sortOrder: 57, icon: "crown" },
  { key: "win_streak_3", category: "performance", tier: "silver", points: 60, sortOrder: 60, icon: "bolt" },
  { key: "win_streak_5", category: "performance", tier: "gold", points: 120, sortOrder: 70, icon: "flame" },
  { key: "rank_top_3", category: "performance", tier: "gold", points: 120, sortOrder: 80, icon: "podium" },
  { key: "rank_1", category: "performance", tier: "platinum", points: 200, sortOrder: 90, icon: "medal" },
  { key: "season_creator", category: "community", tier: "silver", points: 70, sortOrder: 100, icon: "calendar" },
  { key: "seasons_3", category: "community", tier: "silver", points: 110, sortOrder: 105, icon: "calendar" },
  { key: "seasons_5", category: "community", tier: "gold", points: 180, sortOrder: 107, icon: "calendar" },
  { key: "season_played", category: "community", tier: "bronze", points: 30, sortOrder: 108, icon: "calendar" },
  { key: "seasons_played_3", category: "community", tier: "silver", points: 75, sortOrder: 109, icon: "calendar" },
  { key: "seasons_played_5", category: "community", tier: "gold", points: 140, sortOrder: 110, icon: "calendar" },
  { key: "tournament_creator", category: "community", tier: "silver", points: 80, sortOrder: 120, icon: "bracket" },
  { key: "tournaments_3", category: "community", tier: "silver", points: 120, sortOrder: 125, icon: "bracket" },
  { key: "tournaments_5", category: "community", tier: "gold", points: 190, sortOrder: 127, icon: "bracket" },
  { key: "tournament_played", category: "community", tier: "bronze", points: 35, sortOrder: 128, icon: "bracket" },
  { key: "tournaments_played_3", category: "community", tier: "silver", points: 85, sortOrder: 129, icon: "bracket" },
  { key: "tournaments_played_5", category: "community", tier: "gold", points: 150, sortOrder: 130, icon: "bracket" },
  { key: "elo_1250", category: "performance", tier: "bronze", points: 40, sortOrder: 140, icon: "podium" },
  { key: "elo_1350", category: "performance", tier: "silver", points: 90, sortOrder: 141, icon: "podium" },
  { key: "elo_1500", category: "performance", tier: "gold", points: 170, sortOrder: 142, icon: "medal" },
  { key: "elo_1700", category: "performance", tier: "platinum", points: 300, sortOrder: 143, icon: "medal" },
  { key: "days_30", category: "onboarding", tier: "bronze", points: 30, sortOrder: 150, icon: "spark" },
  { key: "days_180", category: "community", tier: "silver", points: 90, sortOrder: 151, icon: "calendar" },
  { key: "days_365", category: "community", tier: "gold", points: 180, sortOrder: 152, icon: "calendar" },
] as const;

export type AchievementDefinition = (typeof ACHIEVEMENTS)[number];
export type AchievementKey = AchievementDefinition["key"];
