export const ACHIEVEMENTS = [
  { key: "account_created", category: "onboarding", tier: "bronze", points: 10, sortOrder: 10, icon: "user_plus" },
  { key: "first_match", category: "onboarding", tier: "bronze", points: 20, sortOrder: 20, icon: "ping_pong" },
  { key: "first_win", category: "performance", tier: "bronze", points: 30, sortOrder: 30, icon: "victory_badge" },
  { key: "first_singles", category: "activity", tier: "bronze", points: 25, sortOrder: 32, icon: "single_dot" },
  { key: "singles_10", category: "activity", tier: "silver", points: 70, sortOrder: 33, icon: "bullseye" },
  { key: "first_doubles", category: "activity", tier: "bronze", points: 25, sortOrder: 34, icon: "double_dot" },
  { key: "doubles_10", category: "activity", tier: "silver", points: 70, sortOrder: 34, icon: "handshake" },
  { key: "matches_3", category: "activity", tier: "bronze", points: 25, sortOrder: 35, icon: "three_mark" },
  { key: "matches_5", category: "activity", tier: "bronze", points: 35, sortOrder: 37, icon: "five_mark" },
  { key: "matches_10", category: "activity", tier: "silver", points: 50, sortOrder: 40, icon: "ten_mark" },
  { key: "matches_25", category: "activity", tier: "gold", points: 100, sortOrder: 50, icon: "twentyfive_mark" },
  { key: "matches_50", category: "activity", tier: "gold", points: 150, sortOrder: 55, icon: "fifty_mark" },
  { key: "matches_100", category: "activity", tier: "platinum", points: 260, sortOrder: 57, icon: "hundred_mark" },
  { key: "win_streak_3", category: "performance", tier: "silver", points: 60, sortOrder: 60, icon: "lightning_run" },
  { key: "win_streak_5", category: "performance", tier: "gold", points: 120, sortOrder: 70, icon: "wildfire" },
  { key: "perfect_11_0", category: "performance", tier: "silver", points: 75, sortOrder: 72, icon: "perfect_11_badge" },
  { key: "perfect_21_0", category: "performance", tier: "gold", points: 130, sortOrder: 73, icon: "perfect_21_badge" },
  { key: "blowout_11_4", category: "performance", tier: "silver", points: 70, sortOrder: 74, icon: "blowout_11_badge" },
  { key: "blowout_21_9", category: "performance", tier: "gold", points: 120, sortOrder: 74, icon: "blowout_21_badge" },
  { key: "rank_top_10", category: "performance", tier: "silver", points: 80, sortOrder: 75, icon: "top_ten_badge" },
  { key: "rank_top_3", category: "performance", tier: "gold", points: 120, sortOrder: 80, icon: "podium_finish" },
  { key: "rank_1", category: "performance", tier: "platinum", points: 200, sortOrder: 90, icon: "gold_medal" },
  { key: "season_creator", category: "community", tier: "silver", points: 70, sortOrder: 100, icon: "calendar_plus" },
  { key: "seasons_3", category: "community", tier: "silver", points: 110, sortOrder: 105, icon: "calendar_stack" },
  { key: "seasons_5", category: "community", tier: "gold", points: 180, sortOrder: 107, icon: "calendar_archive" },
  { key: "season_played", category: "community", tier: "bronze", points: 30, sortOrder: 108, icon: "leaf_one" },
  { key: "seasons_played_3", category: "community", tier: "silver", points: 75, sortOrder: 109, icon: "leaf_three" },
  { key: "seasons_played_5", category: "community", tier: "gold", points: 140, sortOrder: 110, icon: "leaf_five" },
  { key: "season_podium", category: "community", tier: "silver", points: 90, sortOrder: 111, icon: "season_podium_badge" },
  { key: "season_winner", category: "community", tier: "gold", points: 160, sortOrder: 112, icon: "season_winner_badge" },
  { key: "season_podiums_3", category: "community", tier: "gold", points: 180, sortOrder: 113, icon: "season_podiums_badge" },
  { key: "season_wins_3", category: "community", tier: "platinum", points: 260, sortOrder: 114, icon: "season_dynasty_badge" },
  { key: "tournament_creator", category: "community", tier: "silver", points: 80, sortOrder: 120, icon: "bracket_seed" },
  { key: "tournaments_3", category: "community", tier: "silver", points: 120, sortOrder: 125, icon: "bracket_triplet" },
  { key: "tournaments_5", category: "community", tier: "gold", points: 190, sortOrder: 127, icon: "bracket_crown" },
  { key: "tournament_played", category: "community", tier: "bronze", points: 35, sortOrder: 128, icon: "ticket_one" },
  { key: "tournaments_played_3", category: "community", tier: "silver", points: 85, sortOrder: 129, icon: "ticket_three" },
  { key: "tournaments_played_5", category: "community", tier: "gold", points: 150, sortOrder: 130, icon: "ticket_five" },
  { key: "tournament_finalist", category: "community", tier: "silver", points: 95, sortOrder: 131, icon: "tournament_finalist_badge" },
  { key: "tournament_winner", category: "community", tier: "gold", points: 170, sortOrder: 132, icon: "tournament_winner_badge" },
  { key: "tournament_finals_3", category: "community", tier: "gold", points: 190, sortOrder: 133, icon: "tournament_finals_badge" },
  { key: "tournament_wins_3", category: "community", tier: "platinum", points: 280, sortOrder: 134, icon: "tournament_dynasty_badge" },
  { key: "elo_1250", category: "performance", tier: "bronze", points: 40, sortOrder: 140, icon: "chart_up" },
  { key: "elo_1350", category: "performance", tier: "silver", points: 90, sortOrder: 141, icon: "chart_peak" },
  { key: "elo_1500", category: "performance", tier: "gold", points: 170, sortOrder: 142, icon: "diamond_rank" },
  { key: "elo_1700", category: "performance", tier: "platinum", points: 300, sortOrder: 143, icon: "rocket_rank" },
  { key: "days_30", category: "onboarding", tier: "bronze", points: 30, sortOrder: 150, icon: "moon_cycle" },
  { key: "days_180", category: "community", tier: "silver", points: 90, sortOrder: 151, icon: "sun_path" },
  { key: "days_365", category: "community", tier: "gold", points: 180, sortOrder: 152, icon: "party_year" },
] as const;

export type AchievementDefinition = (typeof ACHIEVEMENTS)[number];
export type AchievementKey = AchievementDefinition["key"];
