name = "spinrank-api"
main = "src/index.ts"
compatibility_date = "2026-04-01"

[[d1_databases]]
binding = "DB"
database_name = "spinrank-prod"
database_id = "c679ee8a-9171-4be9-b12a-c8db73cbc38f"
preview_database_id = "679ee8a-9171-4be9-b12a-c8db73cbc38f"
migrations_dir = "migrations"

[vars]
APP_ENV = "prod"
APP_ORIGIN = "https://spinrank.eu"

[env.dev]
  [[env.dev.d1_databases]]
  binding = "DB"
  database_name = "spinrank-db"
  database_id = "52580792-81e8-423f-8f4b-6561b2434363"
  preview_database_id = "52580792-81e8-423f-8f4b-6561b2434363"
  migrations_dir = "migrations"

  [env.dev.vars]
  APP_ENV = "dev"
  APP_ORIGIN = "http://localhost:5173"

[env.e2e]
  [[env.e2e.d1_databases]]
  binding = "DB"
  database_name = "spinrank-e2e-db"
  database_id = "00000000-0000-0000-0000-000000000000"
  preview_database_id = "00000000-0000-0000-0000-000000000000"
  migrations_dir = "migrations"

  [env.e2e.vars]
  APP_ENV = "test"
  APP_ORIGIN = "http://localhost:4173"
  TEST_AUTH_SECRET = "test-auth-secret"
  DISABLE_RATE_LIMIT = "1"
